spring.application.name=erecepta-server
spring.datasource.url=jdbc:mysql://localhost:3306/e_recepta
spring.datasource.username=root
spring.datasource.password=haslo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true